# Generated by Django 5.0.6 on 2024-06-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns_app', '0003_rename_requested_id_friendrequests_requested_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequests',
            old_name='reuest_status',
            new_name='request_status',
        ),
    ]
